### ISSUE TITLE
Does not detect status of hyphenated project names

### ISSUE THREAD

**Issue by Ceralor** [nsano-rururu/docker-compose-ui#18]
As stated, I have my Home Assistant project in `dockers/home-assistant/` with ALMOST all volumes there but some are Docker volumes. docker-compose-ui original has this issue, and as it's archived it won't be fixed, so the fork seems to still have it too. As a result it only detects the state once the UI has generated the project, and also does so by creating volumes without the hyphens, causing confusion for compose on the machine itself.

I also see my DB container named `db_1` which is not the same name the host's compose creates but this is unrelated and not a huge issue.

**Comment by nsano-rururu** [comment]
Then make a pull request

**Comment by nsano-rururu** [comment]
[dockerの命名で落とし穴](https://qiita.com/koooge/items/5d1fa996e03a701e9d39)
> これについて議論されていますが、scaleとコンテナ名は正反対なものだと言われています。また、composeのドキュメントにも記載されています。
> container_nameを削除すると、コンテナ名は、<COMPOSE_PROJECT_NAME>_<service名>_<ID>とdocker-composeにより命名されます。ドキュメントにも記載があります。
> 下記の例では、プロジェクト名をhoge-projectとすると、コンテナ名は、hogeproject_app_1、 hogeproject_app_2となっています。

**Comment by nsano-rururu** [comment]
Since we decided to use discussions, we will close existing issues.
https://github.com/nsano-rururu/docker-compose-ui/discussions
