### ISSUE TITLE
Upstream maintainer(s)

### ISSUE THREAD

**Issue by binarymist** [nsano-rururu/docker-compose-ui#31]
Hi Naoyuki, are you now maintaining docker-compose-ui now that upstream has been archived?

**Comment by nsano-rururu** [comment]
Yes

**Comment by nsano-rururu** [comment]
So far, I'm not thinking about adding any new features.

**Comment by binarymist** [comment]
My project ([purpleteam](https://github.com/purpleteam-labs)) depends on docker-compose-ui. What is your plan with all the open PRs and issues from upstream?

**Comment by binarymist** [comment]
Just a thought for you... these sorts of discussions are well served with Github Discussions. [purpleteam Discussions](https://github.com/purpleteam-labs/purpleteam/discussions) for example

**Comment by nsano-rururu** [comment]
@binarymist

There are no particular plans at this time. We will consider responding if there is a request, but we cannot promise that we will respond by any time.
Discuss about adding features in discussions
https://github.com/nsano-rururu/docker-compose-ui/discussions

**Comment by nsano-rururu** [comment]
Since we decided to use discussions, we will close existing issues.
https://github.com/nsano-rururu/docker-compose-ui/discussions
